### ISSUE TITLE
Access the drawing in Shiny server

### ISSUE THREAD

**Issue by dcaud** [feddelegrand7/fabricerin#5]
Great package! 

Is there a way to access what is drawn Shiny Server? For example, say I draw some lines. Then I want to add some image processing (like blurring using Image Magick). Is there a plan to include that kind of workflow in fabricerin?

**Comment by feddelegrand7** [comment]
Hi @dcaud thank you very much, I appreciate it. Unfortunately, on my side I don't plan to implement fabricerin functions within the server. Nevertheless you can still use uiOutput() and renderUI() to trigger some reactivity. Did you try these options ?
